### ISSUE TITLE
The lyrics dont scroll at the correct speed

### ISSUE THREAD

**Issue by brendjuan** [britchken/quantum-safari#1]
I noticed, when playing any of the songs, the lyrics do not scroll at the correct speed. 

I like how the Apple Music lyrics scroll, maybe you should do them that way!

**Comment by britchken** [comment]
This issue is not a problem, but rather an indication of success. I’m going to close this.

**Comment by brendjuan** [comment]
No way this is not an indication of success. This is a problem that must be stopped

**Comment by brendjuan** [comment]
wait this isnt fixed

**Comment by britchken** [comment]
Go listen to Apple Music.
